<?php

namespace Database\Seeders;

use App\Models\Member;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('members')->insert([
            // Teras
            [
                "name" => "Aliem Maharits",
                "position" => "Ketua Umum",
                "photo" => "member-photos/aliem.png",
                "division_id" => 1,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Atururi Husaini Fadillah",
                "position" => "Wakil Ketua Umum",
                "photo" => "member-photos/fadil.png",
                "division_id" => 1,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Rezkya Nurdiani",
                "position" => "Sekretaris Umum",
                "photo" => "member-photos/diani.png",
                "division_id" => 1,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Meisya Athaya",
                "position" => "Bendahara Umum",
                "photo" => "member-photos/meisya.png",
                "division_id" => 1,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Koordinator
            [
                "name" => "Hary Setiawan",
                "position" => "Koordinator Bukit Indah",
                "photo" => "member-photos/hary.png",
                "division_id" => 2,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Deni Ariadi",
                "position" => "Koordinator Reuleut",
                "photo" => "member-photos/deni.png",
                "division_id" => 2,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "M. Ridha Irvan",
                "position" => "Koordinator Poltek",
                "photo" => "member-photos/irvan.png",
                "division_id" => 2,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "M. Rifky Abdallah Syafendi",
                "position" => "Koordinator IAIN",
                "photo" => "member-photos/rifky.png",
                "division_id" => 2,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Putri Raudhatul Muna",
                "position" => "Koordinator Poltekkes",
                "photo" => "member-photos/putri.png",
                "division_id" => 2,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Muhammad Jeskin Namuska",
                "position" => "Koordinator Kota",
                "photo" => "member-photos/jeskin.png",
                "division_id" => 2,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Agama
            [
                "name" => "Zulfikri",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/zulfikri.png",
                "division_id" => 3,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Putri Maulida",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/maulida.png",
                "division_id" => 3,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Yusril",
                "position" => "Anggota",
                "photo" => "member-photos/yusril.png",
                "division_id" => 3,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Nadia Amanda",
                "position" => "Anggota",
                "photo" => "member-photos/amanda.png",
                "division_id" => 3,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Ramadhania",
                "position" => "Anggota",
                "photo" => "member-photos/ramadhania.png",
                "division_id" => 3,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Kaderisasi
            [
                "name" => "Tri Suhandina",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/tri.png",
                "division_id" => 4,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Ihsan Zul Ansar",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/ihsan.png",
                "division_id" => 4,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Aldi Juwanda",
                "position" => "Anggota",
                "photo" => "member-photos/aldi.png",
                "division_id" => 4,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Arlian Ramadhan",
                "position" => "Anggota",
                "photo" => "member-photos/arlian.png",
                "division_id" => 4,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Darmala Hayati",
                "position" => "Anggota",
                "photo" => "member-photos/darmala.png",
                "division_id" => 4,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Putri Ulfah Syaridha",
                "position" => "Anggota",
                "photo" => "member-photos/ulfah.png",
                "division_id" => 4,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Rizki Iqbal Fauzi",
                "position" => "Anggota",
                "photo" => "member-photos/fauzi.png",
                "division_id" => 4,
                "sort" => 7,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Srey Nazwa Dian Madina",
                "position" => "Anggota",
                "photo" => "member-photos/nazwa.png",
                "division_id" => 4,
                "sort" => 8,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Syabina Putri Rahma",
                "position" => "Anggota",
                "photo" => "member-photos/syabina.png",
                "division_id" => 4,
                "sort" => 9,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Yadika Atmaja",
                "position" => "Anggota",
                "photo" => "member-photos/yadika.png",
                "division_id" => 4,
                "sort" => 10,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Kesekretariatan
            [
                "name" => "Wanda Baskoro",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/wanda.png",
                "division_id" => 5,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Dinda Pratiwi",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/dinda.png",
                "division_id" => 5,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Andini",
                "position" => "Anggota",
                "photo" => "member-photos/andini.png",
                "division_id" => 5,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Delia Permata Sari",
                "position" => "Anggota",
                "photo" => "member-photos/delia.png",
                "division_id" => 5,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Meisya Aprilia",
                "position" => "Anggota",
                "photo" => "member-photos/aprilia.png",
                "division_id" => 5,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Mutia Sari",
                "position" => "Anggota",
                "photo" => "member-photos/mutia.png",
                "division_id" => 5,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Nurafni",
                "position" => "Anggota",
                "photo" => "member-photos/nurafni.png",
                "division_id" => 5,
                "sort" => 7,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Samsul Bahri",
                "position" => "Anggota",
                "photo" => "member-photos/samsul.png",
                "division_id" => 5,
                "sort" => 8,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Srik Wardhani",
                "position" => "Anggota",
                "photo" => "member-photos/srik.png",
                "division_id" => 5,
                "sort" => 9,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Infokom
            [
                "name" => "Silvia Masyitah",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/silvia.png",
                "division_id" => 6,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Luna Firriyal",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/luna.png",
                "division_id" => 6,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Zulhiz Tami",
                "position" => "Anggota",
                "photo" => "member-photos/tami.png",
                "division_id" => 6,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Alfiya Balqis",
                "position" => "Anggota",
                "photo" => "member-photos/alfiya.png",
                "division_id" => 6,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Mawwaddah",
                "position" => "Anggota",
                "photo" => "member-photos/mawwaddah.png",
                "division_id" => 6,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Humas
            [
                "name" => "Ridho Kurniawan",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/ridho.png",
                "division_id" => 7,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Juwita Ramaini",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/ramaini.png",
                "division_id" => 7,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Risma Yulita",
                "position" => "Anggota",
                "photo" => "member-photos/risma.png",
                "division_id" => 7,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "M. Firdaus",
                "position" => "Anggota",
                "photo" => "member-photos/firdaus.png",
                "division_id" => 7,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Muhammad Havid",
                "position" => "Anggota",
                "photo" => "member-photos/havid.png",
                "division_id" => 7,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Najwa Sakila Parmanta",
                "position" => "Anggota",
                "photo" => "member-photos/najwa.png",
                "division_id" => 7,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Yurika Tri Amanda",
                "position" => "Anggota",
                "photo" => "member-photos/yurika.png",
                "division_id" => 7,
                "sort" => 7,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Rahmadhatulah Rafi Maulana",
                "position" => "Anggota",
                "photo" => "member-photos/maulana.png",
                "division_id" => 7,
                "sort" => 8,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Sulastri Ardhan",
                "position" => "Anggota",
                "photo" => "member-photos/sulastri.png",
                "division_id" => 7,
                "sort" => 9,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // kwh
            [
                "name" => "Aji Priansyah",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/aji.png",
                "division_id" => 8,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Natasya Riska Amalia Hardi",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/amalia.png",
                "division_id" => 8,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Cindi Maharani",
                "position" => "Anggota",
                "photo" => "member-photos/cindi.png",
                "division_id" => 8,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Dwiyana Anggreini",
                "position" => "Anggota",
                "photo" => "member-photos/dwiyana.png",
                "division_id" => 8,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Erna Harmadani",
                "position" => "Anggota",
                "photo" => "member-photos/erna.png",
                "division_id" => 8,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Nurjanah",
                "position" => "Anggota",
                "photo" => "member-photos/nurjanah.png",
                "division_id" => 8,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Seni
            [
                "name" => "Anggi Syafitri",
                "position" => "Ketua",
                "photo" => "member-photos/anggi.png",
                "division_id" => 9,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Darmi Samosir",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/darmi.png",
                "division_id" => 9,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Ade Meliza Tri Amanda",
                "position" => "Anggota",
                "photo" => "member-photos/meliza.png",
                "division_id" => 9,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Desi Syafitri",
                "position" => "Anggota",
                "photo" => "member-photos/desi.png",
                "division_id" => 9,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Frety Sri Rizki",
                "position" => "Anggota",
                "photo" => "member-photos/frety.png",
                "division_id" => 9,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Indah Ayu Lestari",
                "position" => "Anggota",
                "photo" => "member-photos/indah.png",
                "division_id" => 9,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Yasya Almira",
                "position" => "Anggota",
                "photo" => "member-photos/almira.png",
                "division_id" => 9,
                "sort" => 7,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Yunita Anggraeni Simatupang",
                "position" => "Anggota",
                "photo" => "member-photos/yunita.png",
                "division_id" => 9,
                "sort" => 8,
                "created_at" => now(),
                "updated_at" => now(),
            ],

            // Olahraga
            [
                "name" => "M. Syahputra",
                "position" => "Ketua Bidang",
                "photo" => "member-photos/syahputra.png",
                "division_id" => 10,
                "sort" => 1,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Dwi Ariska",
                "position" => "Sekretaris Bidang",
                "photo" => "member-photos/ariska.png",
                "division_id" => 10,
                "sort" => 2,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Muhammad Sufardan",
                "position" => "Anggota",
                "photo" => "member-photos/sufardan.png",
                "division_id" => 10,
                "sort" => 3,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Putra Taufiqurrahman Ariza",
                "position" => "Anggota",
                "photo" => "member-photos/taufiq.png",
                "division_id" => 10,
                "sort" => 4,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Tito Gilang Samudra",
                "position" => "Anggota",
                "photo" => "member-photos/tito.png",
                "division_id" => 10,
                "sort" => 5,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "name" => "Muhammad Maizaki",
                "position" => "Anggota",
                "photo" => "member-photos/maizaki.png",
                "division_id" => 10,
                "sort" => 6,
                "created_at" => now(),
                "updated_at" => now(),
            ],
        ]);
    }
}
